console.info('Hello, World! (You will see this line every time client resources reload)')

onEvent('jei.hide.items', event => {
	// Hide items in JEI here
	// event.hide('minecraft:cobblestone')
})

onEvent('rei.hide.items', event => {
  event.hide('indrev:tungsten_block')
  event.hide('indrev:silver_block')
  event.hide('indrev:lead_block')
  event.hide('indrev:electrum_block')
  event.hide('indrev:bronze_block')
  event.hide('indrev:steel_block')
  event.hide('indrev:tin_block')
  event.hide('indrev:copper_block')
  event.hide('indrev:tungsten_ingot')
  event.hide('indrev:silver_ingot')
  event.hide('indrev:lead_ingot')
  event.hide('indrev:electrum_ingot')
  event.hide('indrev:bronze_ingot')
  event.hide('indrev:steel_ingot')
  event.hide('indrev:tin_ingot')
  event.hide('indrev:copper_ingot')
  event.hide('indrev:tungsten_dust')
  event.hide('indrev:silver_dust')
  event.hide('indrev:lead_dust')
  event.hide('indrev:electrum_dust')
  event.hide('indrev:bronze_dust')
  event.hide('indrev:steel_dust')
  event.hide('indrev:tin_dust')
  event.hide('indrev:copper_dust')
  event.hide('indrev:sulfur_dust')
  event.hide('indrev:coal_dust')
  event.hide('indrev:iron_dust')
  event.hide('indrev:gold_dust')
  event.hide('indrev:diamond_dust')
  event.hide('indrev:tungsten_plate')
  event.hide('indrev:silver_plate')
  event.hide('indrev:lead_plate')
  event.hide('indrev:electrum_plate')
  event.hide('indrev:bronze_plate')
  event.hide('indrev:steel_plate')
  event.hide('indrev:tin_plate')
  event.hide('indrev:copper_plate')
  event.hide('indrev:iron_plate')
  event.hide('indrev:gold_plate')
  event.hide('indrev:tungsten_ore')
  event.hide('indrev:silver_ore')
  event.hide('indrev:lead_ore')
  event.hide('indrev:tin_ore')
  event.hide('indrev:copper_ore')
})