generateOres = true

[ores]
generateAntimony = true
generateBauxite = true
generateCopper = true
generateLead = true
generateLigniteCoal = true
generateNickel = true
generateSalt = true
generateSilver = true
generateTin = true
